name: scheduled-build

on:
  schedule:
    - cron: '17 3 * * *'

jobs:
  scheduled-build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/reusable-build.yml
    with:
      push_image: true
      reason: daily scheduled rebuild
